# .travis.yml for ices-tools packages

# Header
language: r
sudo: false
cache: packages
warnings_are_errors: false

# matrix: 3x Linux, 1x OS X
matrix:
  include:
  - r: release
  - r: oldrel
  - r: devel
  - os: osx
    r: release
    latex: false

# notifications
notifications:
  email:
    on_success: change
    on_failure: change

# repository
repos:
  CRAN: https://cloud.r-project.org

# r_packages
r_packages:
  - icesVocab
  - rmarkdown
  - covr
  - testthat
  - png

r_github_packages:
  - jimhester/lintr

# after_success
after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
