# .travis.yml for ices-tools packages

# Header
language: r
sudo: false
cache: packages
warnings_are_errors: false

# matrix: 3x Linux, 1x OS X
matrix:
  include:
  - r: release
  - r: oldrel
  - r: devel
  - os: osx
    r: release
    latex: false

repos:
  CRAN: https://cloud.r-project.org

r_packages:
  - rmarkdown
  - covr
  - testthat
  - png

notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
  - jimhester/lintr

after_success:
  - Rscript -e 'library(covr);codecov()'
  - Rscript -e 'lintr::lint_package()'
